import enum


class Work(enum.Enum):
    DOCTOR = "DOCTOR"
    EDUCATION_SECTOR = "EDUCATION_SECTOR"
    IT = "IT"
    MANAGER = "MANAGER/ACCOUNTANT/CONSULTANT"
    ENGINEER = "ENGINEER/ARCHITECT/TECHNICIAN"
    DRIVER = "DRIVER"
    PILOT = "PILOT"
    FINANCE_INDUSTRY = "FINANCE_INDUSTRY"
    SALES_FIELD = "SALES_FIELD"
    LOGISTIC_FIELD = "LOGISTIC_FIELD"
    CREATIVE_FIELD = "CREATIVE_FIELD"
    MEDIA_FIELD = "MEDIA_FIELD"
    RESEARCH_SECTOR = "RESEARCH_SECTOR"
    STATE_STRUCTURE = "STATE_STRUCTURE"
    AGRICULTURAL_SECTOR = "AGRICULTURAL_SECTOR"
    UNEMPLOYED = "UNEMPLOYED"
    STUDENT = "STUDENT"
    RETIRED = "RETIRED"
    SELF_EMPLOYED = "SELF_EMPLOYED"


class WorkExperience(enum.Enum):
    LACK_OF_EXPERIENCE = "LACK_OF_EXPERIENCE"
    LESS_THAN_MONTH = "LESS_THAN_MONTH"
    FROM_ONE_TO_THREE_MONTHS = "FROM_ONE_TO_THREE_MONTHS"
    FROM_THREE_TO_SIX_MONTHS = "FROM_THREE_TO_SIX_MONTHS"
    FROM_SIX_TO_TWELVE_MONTHS = "FROM_SIX_TO_TWELVE_MONTHS"
    FROM_ONE_TO_THREE_YEARS = "FROM_ONE_TO_THREE_YEARS"
    MORE_THAN_THREE_YEARS = "MORE_THAN_THREE_YEARS"


class AccountType(enum.Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"
    SAVINGS = "SAVINGS"


class CardType(enum.Enum):
    VISA = "VISA"
    MASTERCARD = "MASTERCARD"


class Currency(enum.Enum):
    USD = "USD"
    EUR = "EUR"


class KYCStatus(enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AccountStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"


class CardStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    EXPIRED = "EXPIRED"


class PaymentStatus(enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TransactionStatus(enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class LedgerEntryType(enum.Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class ProductStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    DELINQUENT = "DELINQUENT"
